name: woosignal
description: WooCommerce REST API for dart, connect a WooCommerce store and start developing with our interface for their API endpoints.
version: 3.1.1
homepage: https://woosignal.com
repository: https://github.com/woosignal/flutter-woocommerce-api
issue_tracker: https://github.com/woosignal/flutter-woocommerce-api/issues
documentation: https://woosignal.com/docs/api/1.0/overview

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  device_info_plus: ^4.1.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.19.3